### ISSUE TITLE
데이터 관련 문의

### ISSUE THREAD

**Issue by Moon-sung-woo** [SMART-TTS/SMART-Multi-Speaker-Style-TTS#1]
안녕하세요.
논문과 코드에 대해 잘 읽었습니다.

2022년 초에 데이터를 공개해주신다는 데이터에 대해 문의가 있어 이슈 남깁니다.

1. 공개하신다는 데이터가 정확히 어떤 데이터인지 그리고 emotion TTS에서 공개한다는 데이터와 다른것인지 궁금합니다.
2. emotion TTS에서 공개하겠다고 하신 데이터가 공개 되었는지 궁금합니다.

감사합니다.

**Comment by SMART-TTS** [comment]
안녕하세요,
공개되는 데이터셋은 SMART-TTS 프로젝트를 통해 직접 녹음 및 수집한 데이터셋으로, 다화자 스타일 음성합성을 위한 한국어 데이터셋입니다. Single emotional TTS repository에서 공개한다고했던 데이터셋과 동일한 데이터셋이며, 곧 공개 예정입니다. 공개되는 즉시 SMART-TTS 프로젝트의 각 repo에서 링크를 걸어두어 다운받을 수 있도록 할 예정입니다. 데이터셋의 자세한 정보는 공개시 명시하도록 하겠습니다. 관심 가져주셔서 감사합니다.

**Comment by Moon-sung-woo** [comment]
답변 감사합니다!!

**Comment by seastar105** [comment]
@SMART-TTS 아직 데이터 공개가 안된걸까요?

**Comment by SMART-TTS** [comment]
> @SMART-TTS 아직 데이터 공개가 안된걸까요?

안녕하세요, 아래 링크에서 데이터 확인하실 수 있습니다.
https://aihub.or.kr/aihubdata/data/view.do?currMenu=120&topMenu=100&dataSetSn=637&aihubDataSe=extrldata

감사합니다.
